# Numpy:-

# Array Manipulation:-

1. Reshaping Arrays:-

In [1]:
import numpy as np
arr = np.arange(12) 
print("Original array:")
print(arr)

arr_reshaped = arr.reshape(3, 4)
print("\nReshaped array (3x4 matrix):")
print(arr_reshaped)

arr_reshaped_2d = arr.reshape(6, 2)
print("\nReshaped array (6x2 matrix):")
print(arr_reshaped_2d)


Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array (3x4 matrix):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped array (6x2 matrix):
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


2. Concatenating Arrays

In [2]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

arr_concat_v = np.concatenate((a, b), axis=0)
print("Concatenated along axis 0 (vertical):")
print(arr_concat_v)

arr_concat_h = np.hstack((a, b.T)) 
print("\nConcatenated along axis 1 (horizontal):")
print(arr_concat_h)


Concatenated along axis 0 (vertical):
[[1 2]
 [3 4]
 [5 6]]

Concatenated along axis 1 (horizontal):
[[1 2 5]
 [3 4 6]]


3. Flattening Arrays:-

In [4]:
import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6]])
a_flattened = a.flatten()

print("Original 2D array:")
print(a)

print("\nFlattened array:")
print(a_flattened)


Original 2D array:
[[1 2 3]
 [4 5 6]]

Flattened array:
[1 2 3 4 5 6]


4. Stacking Arrays:-

In [5]:
a = np.array([1, 2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.hstack((a, b))
print(c)

d = np.vstack((a, b))
print(d)

e = np.stack((a, b), axis=1)
print(e)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


5. Splitting Arrays:-

In [6]:
a = np.array([[1, 2],[3,4],[5,6],[7,8]])

left, right = np.hsplit(a, 2)
print("Horizontal split:")
print("Left sub-array:\n", left)
print("Right sub-array:\n", right)


Horizontal split:
Left sub-array:
 [[1]
 [3]
 [5]
 [7]]
Right sub-array:
 [[2]
 [4]
 [6]
 [8]]


6. Appending Elements:-

In [7]:
a = np.array([1, 2, 3,4,5])
b = np.append(a, [6,7])
print(b)  

c = np.array([[1, 2], [3, 4]])
d = np.append(c, [[5, 6]], axis=0)
print(d)

[1 2 3 4 5 6 7]
[[1 2]
 [3 4]
 [5 6]]


7. Inserting Elements:-

In [9]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
b = np.insert(a, 5, [10, 20])
print(b) 

c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
d = np.insert(c, 2, [10, 20], axis=1)
print(d)

[ 1  2  3  4  5 10 20  6  7  8]
[[ 1  2 10  3  4]
 [ 5  6 20  7  8]]


8. Deleting Elements :-

In [11]:
a = np.array([1, 2, 3])
b = np.delete(a, [0, 2])
print(b) 

c = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
d = np.delete(c, 1, axis=1)
print(d)

[2]
[[ 1  3  4  5]
 [ 6  8  9 10]]


# Pandas:- A Library for Handling Structured Data in Python


Pandas is a high-performance Python library designed for data manipulation and analysis. It provides flexible and powerful tools for working with structured data, allowing you to perform complex operations with minimal code. Some key features of Pandas include:

DataFrames and Series: Pandas uses DataFrames (2D tables) and Series (1D arrays) to represent structured data, similar to tables in a database or Excel.
Comprehensive Data Operations: With Pandas, you can filter, sort, group, merge, concatenate, pivot, and reshape data with ease.
Handling Missing Data: Pandas offers a variety of methods to detect and handle missing or null values.
Integration with Other Libraries: Pandas integrates well with other Python libraries used in data science, like NumPy, SciPy, and

In [4]:
# To check which version you are using 
import pandas as pd
print("Pandas version:", pd.__version__)

Pandas version: 2.2.2


Creation:-

In [8]:
# From Lists
import pandas as pd
data = [101,102,103,104,105]
s = pd.Series(data, index=["a","b","c","d","e"])

print("Series from list")
print(s)

Series from list
a    101
b    102
c    103
d    104
e    105
dtype: int64


In [12]:
# From Arrays:-
import pandas as pd
import numpy as np
array_data = np.array([1.1,2.2,3.3,5.5,7.7])
s_from_array = pd.Series(array_data,index=["i","j","k","l","m"])

print("Series from array:" )
print(s_from_array)

Series from array:
i    1.1
j    2.2
k    3.3
l    5.5
m    7.7
dtype: float64


In [14]:
# From Dictionaries:-
d_data ={"Vansh":1,"Raman":2,"Riya":3}
s_from_d = pd.Series(d_data)

print("Series from dictionary:")
print(s_from_d)

Series from dictionary:
Vansh    1
Raman    2
Riya     3
dtype: int64


#   Attributes

1. s.index:- Returns the index labels of the Series.

In [15]:
import pandas as pd
data = [10, 20, 30]
s = pd.Series(data, index=['a', 'b', 'c'])
print(s.index)


Index(['a', 'b', 'c'], dtype='object')


2. s.values:- Returns the underlying values in the Series as a NumPy array

In [16]:
print(s.values)

[10 20 30]


3. s.dtype:- Provides the data type of the Series element.

In [17]:
print(s.dtype)


int64


4. s.size:- Returns the number of elements in the Series.

In [18]:
print(s.size)

3


# Methods:-

1. s.head(n):- Returns the first'n' elements of the Series.

In [19]:
s = pd.Series([10, 20, 30, 40, 50])
print(s.head(3))


0    10
1    20
2    30
dtype: int64


2. s.tail(n):- Returns the last'n' elements of the Series.

In [20]:
print(s.tail(2))


3    40
4    50
dtype: int64


3. s.sort_values():- Sorts the Series by its values.

In [21]:
data = [50, 20, 30, 10, 40]
s = pd.Series(data)
print(s.sort_values())


3    10
1    20
2    30
4    40
0    50
dtype: int64


4. s.mean(),s.median(), s.std() :-Compute common statistics (mean, median, and standard deviation).

In [22]:
print("Mean:", s.mean())
print("Median:", s.median())
print("Standard Deviation:", s.std())


Mean: 30.0
Median: 30.0
Standard Deviation: 15.811388300841896


5. s.str:- Provides string manipulation methods if the Series contains the string data

In [23]:
data = ['apple', 'papaya', 'cherry']
s = pd.Series(data)
print(s.str.upper())


0     APPLE
1    PAPAYA
2    CHERRY
dtype: object


6. s.apply(function):- Applies a function to each element in the series

In [24]:
data = [1, 2, 3, 4, 5]
s = pd.Series(data)
print(s.apply(lambda x: x ** 2))


0     1
1     4
2     9
3    16
4    25
dtype: int64
