# NumPy:-

NumPy is a powerful Python library used primarily for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in scientific computing, data analysis, and machine learning due to its speed and ease of use for numerical operations.

# NumPy Arrays :-

1D Array (One-dimensional Array):



A 1D array is a collection of elements which are ordered in a single sequence.
It is similar to a list in Python but with more functionalities for numerical computations.



Characteristics:
Indexed by a single index (like a list).
Used for representing vectors or sequences of data.

2D Array (Two-dimensional Array):

A 2D array is essentially a matrix consisting of rows and columns.

Each element in a 2D array is identified by two indices (row index and column index).


Characteristics:
Indexed by two indices (row and column).
Used for representing matrices or tables of data.
Rows and columns can have different lengths.

3D Array (Three-dimensional Array):-

A 3D array can be thought of as a cube of data with multiple layers.
It extends the concept of matrices into three dimensions by adding a depth dimension.


Characteristics:
Indexed by three indices (depth, row, and column).
Used for representing volumetric data, such as a stack of matrices or a cube of data.
Each element is accessed using three indices.

Shape:- It returns a tuple where each element represents the size of the array along a specific dimension.

In [1]:
# 1D Array:-
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.shape) 


(5,)


In [2]:
# 2D Array:-
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
# Ans will be :- 
#For the array b, the shape is (2, 3):
#2 indicates that there are 2 rows.
#3 indicates that each row has 3 columns.


(2, 3)


In [3]:
# 3D Array:-
import numpy as np
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.shape)
# Ans will
#For the array c, the shape is (2, 2, 2):
#2 indicates that there are 2 matrices (or layers).
#2 indicates that each matrix has 2 rows.
#2 indicates that each row has 2 columns.

(2, 2, 2)


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.size)

6


In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.dtype)

int64


In [7]:
d = np.array([True, False, True])
print(d.dtype)  

bool


# Characteristics:-

1. np.array(): Create an array from a Python list or sequence.

In [8]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)


[1 2 3 4 5]


2. np.asarray(): Convert the input to an array.

In [10]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
my_array = np.asarray(my_list)

print(my_array)


[1 2 3 4 5]


3. np.ones(): Create an array filled with ones.

In [ ]:
import numpy as np
b = np.ones((2, 3, 2))
# 2,3,2 is the shape
print(b)


4. np.zeros(): Create an array filled with zeros.

In [11]:
import numpy as np
zeros_array = np.zeros((2, 3, 2))
print(zeros_array)


[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


5. np.arange(): Create a sequence of numbers within a range.

In [19]:
import numpy as np
a = np.arange(50)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


6. np.linspace(): Create an array with evenly spaced values within a range.

In [20]:
a = np.linspace(1,3,7)
print(a)

[1.         1.33333333 1.66666667 2.         2.33333333 2.66666667
 3.        ]


7. np.eye(): Create a square identity matrix.

In [21]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Operations:-

1. Basic Array Operations

In [22]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Array 1:", arr1)
print("Array 2:", arr2)

# Addition :-
addition = arr1 + arr2
print( "addition:",addition)

# Subtraction:-
subtraction = arr2 - arr1
print("subtraction:",subtraction)

# Multiplication:-
multiplication = arr1 * arr2
print("multiplication:", multiplication)

# Division:-
division = arr2 / arr1
print("division:",division)

# Square root
arr_sqrt = np.sqrt(arr1)
print("Square root of Array 1:", arr_sqrt)

# Exponential (e^x)
arr_exp = np.exp(arr1)
print("Exponential of Array 1:", arr_exp)

# Scalar operations
scalar = 2

# Scalar multiplication
scalar_mult = arr1 * scalar
print(f"Scalar multiplication of Array 1 by {scalar}:", scalar_mult)

# Scalar addition
scalar_add = arr2 + scalar
print(f"Scalar addition of Array 2 by {scalar}:", scalar_add)

# Dot product
dot_product = np.dot(arr1, arr2)
print("Dot product:", dot_product)


Array 1: [1 2 3]
Array 2: [4 5 6]
addition: [5 7 9]
subtraction: [3 3 3]
multiplication: [ 4 10 18]
division: [4.  2.5 2. ]
Square root of Array 1: [1.         1.41421356 1.73205081]
Exponential of Array 1: [ 2.71828183  7.3890561  20.08553692]
Scalar multiplication of Array 1 by 2: [2 4 6]
Scalar addition of Array 2 by 2: [6 7 8]
Dot product: 32


2. Broadcasting:-

In [23]:
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
a = arr1 + arr2

print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("A:")
print(a)


Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[10 20 30]
A:
[[11 22 33]
 [14 25 36]]


# Indexing:-

In [24]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print("First element:", a[0])      
print("Third element:", a[2])      
print("Last element:", a[-1])      
print("Second last element:", a[-2]) 


First element: 1
Third element: 3
Last element: 5
Second last element: 4


# Slicing:-

In [30]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Elements from index 2 to 5:", a[2:5])            
print("Reverse the array:", a[::-1])


Elements from index 2 to 5: [3 4 5]
Reverse the array: [10  9  8  7  6  5  4  3  2  1]


In [31]:
import numpy as np
b = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(b[1, 2])        
print(b[:2, :])     
print(b[:, 1])       

6
[[1 2 3]
 [4 5 6]]
[2 5 8]


# Practice Question:-

1. Given a 3D array a with shape (2, 3, 4) and a 2D array b with shape (3, 4), perform element-wise multiplication between a and b using broadcasting.

In [32]:
import numpy as np
a = np.arange(24).reshape(2, 3, 4)
print("Array a:")
print(a)
print("Shape of a:", a.shape)

b = np.arange(12).reshape(3, 4)
print("\nArray b:")
print(b)
print("Shape of b:", b.shape)

result = a * b
print("\nResult of element-wise multiplication:")
print(result)
print("Shape of result:", result.shape)


Array a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape of a: (2, 3, 4)

Array b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape of b: (3, 4)

Result of element-wise multiplication:
[[[  0   1   4   9]
  [ 16  25  36  49]
  [ 64  81 100 121]]

 [[  0  13  28  45]
  [ 64  85 108 133]
  [160 189 220 253]]]
Shape of result: (2, 3, 4)
